package service

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/hasan1808/pro-ui/database/model"
	"github.com/hasan1808/pro-ui/util/random"
)

// GRE-over-IPsec.
//
// GRE has no encryption of its own, which is the one genuinely weak thing about it. The
// standard answer for router customers is to wrap protocol 47 in ESP TRANSPORT mode, and
// this panel already runs a shared strongSwan charon for IKEv2 and L2TP, so terminating it
// costs one more conf.d file rather than a new daemon.
//
// Transport (not tunnel) mode is the right choice: GRE already provides the encapsulation,
// so tunnel mode would add a second, redundant IP header and cost 20 more bytes of MTU. It
// is also exactly what the MikroTik recipe configures (`tunnel=no`).
//
// Enforcement of "IPsec only" is NOT done here but in nftables, by matching whether a
// protocol-47 packet arrived with an XFRM security path attached. That mirrors how L2TP
// gates its own UDP/1701 and is verified end to end: an ESP-wrapped peer keeps working
// while a bare-GRE peer from another address is dropped.

// greIpsecConfName is the shared-charon conf.d file for one GRE inbound. Each protocol owns
// its own file and swanctl.conf includes conf.d/*.conf, so GRE, IKEv2 and L2TP merge into
// one charon without clobbering each other.
func greIpsecConfName(inboundID int) string {
	return fmt.Sprintf("%s/gre-%d.conf", swanctlConfDir, inboundID)
}

// randomPsk mints a pre-shared key for a freshly enabled IPsec toggle.
func randomPsk() string { return random.Seq(24) }

// greIkeID is the IKE identity the panel presents for one GRE inbound, and the identity its
// PSK is scoped to.
//
// This is NOT decoration. The charon is SHARED, and an id-less `secrets` entry matches every
// peer, so two id-less pre-shared keys (L2TP already ships one) leave charon no way to pick
// the right key: it signs the AUTH payload with whichever it finds first and the peer rejects
// it with "tried 1 shared key ... but MAC mismatched". Scoping the secret to a distinct
// identity makes the lookup deterministic and, just as importantly, stops GRE's key from
// being offered to an L2TP peer. Same fix the IKEv2 eap-tls inbound already uses (its own
// IDr) for the same reason.
func greIkeID(inboundID int) string {
	return fmt.Sprintf("gre-%d.vpn-ui", inboundID)
}

// syncIpsec rewrites every GRE inbound's swanctl connection and reloads the shared charon.
// Called from SetupRouting, so it follows the same path as any other settings change.
func (s *GreService) syncIpsec() error {
	inbounds, err := s.GetGreInbounds()
	if err != nil {
		return err
	}

	wanted := map[string]bool{}
	for _, inbound := range inbounds {
		settings, err := s.parseSettings(inbound)
		if err != nil || !inbound.Enable || !settings.IpsecEnable {
			continue
		}
		if strings.TrimSpace(settings.IpsecPsk) == "" {
			continue // nothing to authenticate with; ReconcilePeers mints one on save
		}
		path := greIpsecConfName(inbound.Id)
		if err := s.writeGreSwanctlConn(inbound, settings, path); err != nil {
			return err
		}
		wanted[path] = true
	}

	// Drop connections for inbounds that no longer want IPsec (or were deleted), so charon
	// stops offering a PSK for them.
	if matches, err := filepath.Glob(swanctlConfDir + "/gre-*.conf"); err == nil {
		for _, m := range matches {
			if !wanted[m] {
				_ = os.Remove(m)
			}
		}
	}

	return syncCharon()
}

// writeGreSwanctlConn writes one inbound's IKE connection: PSK auth, ESP transport mode,
// traffic selectors narrowed to protocol 47.
func (s *GreService) writeGreSwanctlConn(inbound *model.Inbound, settings *greSettings, path string) error {
	_ = os.MkdirAll(swanctlConfDir, 0755)
	body := applyCoreConfigOverride("gre", inbound.Id, fmt.Sprintf("gre-%d.conf", inbound.Id),
		s.buildGreSwanctlConn(inbound, settings))
	return os.WriteFile(path, []byte(body), 0600)
}

// buildGreSwanctlConn renders the body. Split from the write so the config editor can
// show the operator the GENERATED text they are diverging from; the file on disk already
// has their override merged in.
func (s *GreService) buildGreSwanctlConn(inbound *model.Inbound, settings *greSettings) string {
	esc := strings.ReplaceAll(settings.IpsecPsk, `\`, `\\`)
	esc = strings.ReplaceAll(esc, `"`, `\"`)

	var b strings.Builder
	b.WriteString("# Auto-generated by pro-ui GRE service (ESP transport on shared charon) - do not edit\n")
	b.WriteString("connections {\n")
	b.WriteString(fmt.Sprintf("    gre-%d {\n", inbound.Id))
	// version 0 = accept IKEv1 OR IKEv2. Routers differ on which they offer by default
	// (RouterOS defaults to IKEv1 in older releases, IKEv2 in newer), and the whole point of
	// this protocol is to work on whatever the customer already owns.
	b.WriteString("        version = 0\n")
	b.WriteString("        remote_addrs = %any\n")
	b.WriteString("        aggressive = no\n")
	b.WriteString("        mobike = no\n")
	b.WriteString("        rekey_time = 3h\n")
	b.WriteString("        reauth_time = 0s\n")
	b.WriteString("        dpd_delay = 30s\n")
	b.WriteString("        fragmentation = yes\n")
	// Wide proposal list for the same reason as L2TP's: consumer and older enterprise gear
	// offers a narrow, dated set, and a strict list shows up as NO_PROPOSAL_CHOSEN.
	b.WriteString("        proposals = aes256-sha256-modp2048,aes128-sha256-modp2048,aes256-sha1-modp2048,aes128-sha1-modp2048,aes256gcm16-prfsha256-ecp256,aes256-sha1-modp1536,aes256-sha1-modp1024,aes128-sha1-modp1024,3des-sha1-modp1024,default\n")
	// A distinct local identity, so charon can tell this connection's PSK apart from every
	// other id-less one on the shared daemon. The peer sets it as its remote id.
	b.WriteString(fmt.Sprintf("        local {\n            auth = psk\n            id = %s\n        }\n",
		greIkeID(inbound.Id)))
	// No remote id: a dynamic-address peer cannot be pinned to one, and the PSK is the
	// credential either way.
	b.WriteString("        remote {\n            auth = psk\n        }\n")
	b.WriteString("        children {\n")
	b.WriteString("            gre {\n")
	b.WriteString("                mode = transport\n")
	// `dynamic` resolves to whichever local address the SA lands on, which is what we want
	// when the panel may listen on several. The protocol qualifier narrows the SA to GRE so
	// nothing else on this host is accidentally swept into it.
	b.WriteString("                local_ts = dynamic[gre]\n")
	b.WriteString("                remote_ts = dynamic[gre]\n")
	b.WriteString("                esp_proposals = aes256gcm16,aes256-sha256,aes128-sha256,aes256-sha1,aes128-sha1,3des-sha1,default\n")
	b.WriteString("                rekey_time = 1h\n")
	b.WriteString("                dpd_action = clear\n")
	// The customer's router initiates; we only respond.
	b.WriteString("                start_action = none\n")
	b.WriteString("            }\n")
	b.WriteString("        }\n")
	b.WriteString("    }\n")
	b.WriteString("}\n")
	b.WriteString("secrets {\n")
	b.WriteString(fmt.Sprintf("    ike-gre-%d {\n", inbound.Id))
	// TWO owners, and both are required.
	//
	// strongSwan matches a PSK by looking up an owner for BOTH ends of the exchange: a
	// secret that lists owners must match `me` AND `other`, and only a secret with no
	// owners at all acts as a full wildcard. Listing just this inbound's identity therefore
	// made the secret unusable (the peer's identity matched no owner), so charon fell back
	// to L2TP's owner-less key, signed the AUTH payload with it, and the peer rejected the
	// exchange with "tried 1 shared key ... but MAC mismatched". Naming the local identity
	// AND %any makes it match this pair while still beating the owner-less key on
	// specificity, so GRE's key is chosen and is not offered to an L2TP peer.
	b.WriteString(fmt.Sprintf("        id_local = %s\n", greIkeID(inbound.Id)))
	b.WriteString("        id_any = %any\n")
	b.WriteString(fmt.Sprintf("        secret = \"%s\"\n", esc))
	b.WriteString("    }\n")
	b.WriteString("}\n")
	return b.String()
}

// greInboundHasIpsec reports whether a gre inbound has IPsec enabled. Unlike L2TP, absence
// means FALSE: GRE's raw mode is the baseline every router supports, so encryption is opt-in
// rather than opt-out.
func greInboundHasIpsec(inbound *model.Inbound) bool {
	if inbound == nil {
		return false
	}
	var st struct {
		IpsecEnable bool   `json:"ipsecEnable"`
		IpsecPsk    string `json:"ipsecPsk"`
	}
	if err := json.Unmarshal([]byte(inbound.Settings), &st); err != nil {
		return false
	}
	return st.IpsecEnable && strings.TrimSpace(st.IpsecPsk) != ""
}
