package service

import (
	"fmt"
	"strings"
	"testing"

	"github.com/hasan1808/pro-ui/database"
	"github.com/hasan1808/pro-ui/database/model"
)

// Per-inbound L2TP/IPsec pre-shared keys.
//
// Two things are being pinned here, and the second matters more than the first:
//
//  1. that a distinct listen address per inbound produces one IKE connection per
//     inbound, with the key scoped to the address that selects it;
//  2. that EVERY other arrangement still produces the single panel-wide connection,
//     byte for byte. Both generators overwrite host files on every panel start, so a
//     stray character here is a diff on every existing install.
//
// The expected panel-wide bodies below are written out in full rather than derived from
// the generators, which is the only way this can catch the generators changing.

// l2tpPskInbound builds an l2tp inbound with IPsec on.
func l2tpPskInbound(id int, listen, psk string) *model.Inbound {
	return &model.Inbound{
		Id: id, Protocol: model.L2TP, Enable: true, Listen: listen,
		Settings: fmt.Sprintf(`{"ipsecEnable":true,"ipsecPsk":%q}`, psk),
	}
}

// wantSwanctlPanelWide is the swanctl connection the panel has always written: one
// `l2tp-psk`, no local_addrs, and an owner-less secret.
const wantSwanctlPanelWide = `# Auto-generated by vpn-ui L2TP service (IKEv1 transport on shared charon) - do not edit
connections {
    l2tp-psk {
        version = 1
        aggressive = no
        mobike = no
        rekey_time = 3h
        reauth_time = 0s
        dpd_delay = 30s
        fragmentation = yes
        proposals = aes256-sha256-modp2048,aes128-sha256-modp2048,aes256-sha1-modp2048,aes128-sha1-modp2048,3des-sha1-modp2048,aes256-sha1-modp1536,3des-sha1-modp1536,aes256-sha1-modp1024,aes128-sha1-modp1024,3des-sha1-modp1024,default
        local {
            auth = psk
        }
        remote {
            auth = psk
        }
        children {
            l2tp {
                mode = transport
                local_ts = dynamic[udp/1701]
                remote_ts = dynamic[udp]
                esp_proposals = aes256-sha256,aes128-sha256,aes256-sha1,aes128-sha1,3des-sha1,default
                rekey_time = 1h
                dpd_action = clear
            }
        }
    }
}
secrets {
    ike-l2tp {
        secret = "first-key"
    }
}
`

// wantIpsecConfPanelWide is libreswan's twin, rendered against a feature set with
// nothing detected (no version, no bundle, no MODP1024) so the text is fixed.
const wantIpsecConfPanelWide = `# Auto-generated by vpn-ui L2TP service — do not edit
config setup
    uniqueids=no
    logfile=/var/log/pluto.log

conn l2tp-psk
    auto=add
    leftprotoport=17/1701
    rightprotoport=17/%any
    type=transport
    authby=secret
    pfs=no
    rekey=no
    dpddelay=40
    dpdtimeout=130
    keyexchange=ike
    ikev2=no
    ike=aes256-sha2;modp2048,aes128-sha2;modp2048,aes256-sha1;modp2048,aes128-sha1;modp2048,3des-sha1;modp2048,aes256-sha2;modp1536,aes128-sha2;modp1536,aes256-sha1;modp1536,aes128-sha1;modp1536,3des-sha1;modp1536,3des-md5;modp1536,aes256-sha2;dh20,aes256-sha2;dh19,aes128-sha2;dh19
    phase2alg=aes256-sha2,aes128-sha2,aes256-sha1,aes128-sha1,3des-sha1,aes256-md5,aes128-md5,3des-md5
    left=%defaultroute
    right=%any
`

// noLibreswanFeatures is a host with nothing detected, which is also what a test box
// without libreswan reports.
var noLibreswanFeatures = libreswanFeatures{}

// sharedListenCases are the arrangements that CANNOT have a key each, and so must keep
// producing exactly what the panel produced before per-inbound keys existed.
var sharedListenCases = []struct {
	name     string
	inbounds []*model.Inbound
}{
	{
		"one inbound, no listen address",
		[]*model.Inbound{l2tpPskInbound(1, "", "first-key")},
	},
	{
		// One inbound has nothing to be told apart from, so it stays on the shape every
		// install already has rather than being rewritten for no gain.
		"one inbound with its own listen address",
		[]*model.Inbound{l2tpPskInbound(1, "10.0.0.1", "first-key")},
	},
	{
		"two inbounds, no listen address, same key",
		[]*model.Inbound{l2tpPskInbound(1, "", "first-key"), l2tpPskInbound(2, "", "first-key")},
	},
	{
		"one listen address and one wildcard: the wildcard answers on both",
		[]*model.Inbound{l2tpPskInbound(1, "", "first-key"), l2tpPskInbound(2, "10.0.0.2", "second-key")},
	},
	{
		"an explicit 0.0.0.0 is a wildcard too",
		[]*model.Inbound{l2tpPskInbound(1, "0.0.0.0", "first-key"), l2tpPskInbound(2, "10.0.0.2", "second-key")},
	},
	{
		"both on the same listen address",
		[]*model.Inbound{l2tpPskInbound(1, "10.0.0.1", "first-key"), l2tpPskInbound(2, "10.0.0.1", "second-key")},
	},
	{
		// A hostname becomes an FQDN identity in IKEv1, which never matches the
		// address-derived identity the key lookup uses.
		"a listen address that is not an IP literal",
		[]*model.Inbound{l2tpPskInbound(1, "vpn.example.com", "first-key"), l2tpPskInbound(2, "10.0.0.2", "second-key")},
	},
	{
		"a disabled inbound is not a second IKE responder",
		[]*model.Inbound{
			l2tpPskInbound(1, "10.0.0.1", "first-key"),
			func() *model.Inbound { ib := l2tpPskInbound(2, "10.0.0.2", "second-key"); ib.Enable = false; return ib }(),
		},
	},
}

func TestL2tpSwanctlConnStaysPanelWideWhenTheAddressCannotSelectAKey(t *testing.T) {
	var svc L2tpService
	for _, tc := range sharedListenCases {
		t.Run(tc.name, func(t *testing.T) {
			if peers := l2tpPerListenPeers(svc.l2tpIpsecPeers(tc.inbounds, true)); len(peers) != 0 {
				t.Fatalf("split into %d per-inbound connections, want the panel-wide one", len(peers))
			}
			if got := svc.buildL2tpSwanctlConn(tc.inbounds); got != wantSwanctlPanelWide {
				t.Errorf("swanctl body changed:\n--- got ---\n%s\n--- want ---\n%s", got, wantSwanctlPanelWide)
			}
		})
	}
}

func TestIpsecConfStaysPanelWideWhenTheAddressCannotSelectAKey(t *testing.T) {
	var svc L2tpService
	for _, tc := range sharedListenCases {
		t.Run(tc.name, func(t *testing.T) {
			// The libreswan generator has always read disabled inbounds too, so it takes
			// the unfiltered list for the panel-wide fallback.
			all := svc.l2tpIpsecPeers(tc.inbounds, false)
			perListen := l2tpPerListenPeers(svc.l2tpIpsecPeers(tc.inbounds, true))
			if len(perListen) != 0 {
				t.Fatalf("split into %d per-inbound conns, want the panel-wide one", len(perListen))
			}
			got := buildIpsecConf(noLibreswanFeatures, ipsecConnsFor(all, perListen))
			if got != wantIpsecConfPanelWide {
				t.Errorf("ipsec.conf changed:\n--- got ---\n%s\n--- want ---\n%s", got, wantIpsecConfPanelWide)
			}
			if secrets := buildIpsecSecrets(all, perListen); secrets != ": PSK \"first-key\"\n" {
				t.Errorf("ipsec.secrets is %q, want the bare wildcard", secrets)
			}
		})
	}
}

// distinctListenInbounds is the one arrangement that CAN hold a key each.
func distinctListenInbounds() []*model.Inbound {
	return []*model.Inbound{
		l2tpPskInbound(1, "10.0.0.1", "first-key"),
		l2tpPskInbound(2, "10.0.0.2", "second-key"),
	}
}

func TestL2tpSwanctlSplitsPerListenAddress(t *testing.T) {
	var svc L2tpService
	peers := l2tpPerListenPeers(svc.l2tpIpsecPeers(distinctListenInbounds(), true))
	if len(peers) != 2 {
		t.Fatalf("got %d per-inbound connections, want 2", len(peers))
	}

	for i, want := range []struct {
		conn, addr, psk string
	}{
		{"l2tp-1", "10.0.0.1", "first-key"},
		{"l2tp-2", "10.0.0.2", "second-key"},
	} {
		body := svc.buildL2tpSwanctlConnFor(peers[i])
		for _, line := range []string{
			"    " + want.conn + " {\n",
			"        local_addrs = " + want.addr + "\n",
			fmt.Sprintf("    ike-%s {\n", want.conn),
			"        id_local = " + want.addr + "\n",
			"        id_any = %any\n",
			fmt.Sprintf("        secret = %q\n", want.psk),
		} {
			if !strings.Contains(body, line) {
				t.Errorf("%s: missing %q in:\n%s", want.conn, line, body)
			}
		}
		// The panel-wide names must be gone, or charon would load two responders for
		// the same addresses and pick between their keys by luck.
		if strings.Contains(body, "    l2tp-psk {") || strings.Contains(body, "    ike-l2tp {") {
			t.Errorf("%s still carries the panel-wide connection or secret name:\n%s", want.conn, body)
		}
		if other := peers[1-i].psk; strings.Contains(body, other) {
			t.Errorf("%s carries the other inbound's key %q", want.conn, other)
		}
	}
}

func TestIpsecConfSplitsPerListenAddress(t *testing.T) {
	var svc L2tpService
	inbounds := distinctListenInbounds()
	all := svc.l2tpIpsecPeers(inbounds, false)
	perListen := l2tpPerListenPeers(svc.l2tpIpsecPeers(inbounds, true))
	if len(perListen) != 2 {
		t.Fatalf("got %d per-inbound conns, want 2", len(perListen))
	}

	conf := buildIpsecConf(noLibreswanFeatures, ipsecConnsFor(all, perListen))
	for _, line := range []string{
		"conn l2tp-psk-1\n", "    left=10.0.0.1\n",
		"conn l2tp-psk-2\n", "    left=10.0.0.2\n",
	} {
		if !strings.Contains(conf, line) {
			t.Errorf("missing %q in:\n%s", line, conf)
		}
	}
	if strings.Contains(conf, "left=%defaultroute") {
		t.Errorf("a per-inbound conn still terminates on %%defaultroute:\n%s", conf)
	}
	// One `config setup`, and the stanzas separated the way libreswan needs.
	if n := strings.Count(conf, "config setup"); n != 1 {
		t.Errorf("got %d `config setup` blocks, want 1", n)
	}
	if !strings.Contains(conf, "    right=%any\n\nconn l2tp-psk-2\n") {
		t.Errorf("the second conn is not separated by a blank line:\n%s", conf)
	}

	want := "10.0.0.1 %any : PSK \"first-key\"\n10.0.0.2 %any : PSK \"second-key\"\n"
	if got := buildIpsecSecrets(all, perListen); got != want {
		t.Errorf("ipsec.secrets is\n%q\nwant\n%q", got, want)
	}
}

// Every conn in the file gets loaded. `ipsec auto --add l2tp-psk` against a file that
// only defines l2tp-psk-1 and l2tp-psk-2 loads nothing at all.
func TestIpsecConnNames(t *testing.T) {
	var svc L2tpService
	inbounds := distinctListenInbounds()
	conf := buildIpsecConf(noLibreswanFeatures,
		ipsecConnsFor(svc.l2tpIpsecPeers(inbounds, false),
			l2tpPerListenPeers(svc.l2tpIpsecPeers(inbounds, true))))

	got := ipsecConnNames(conf)
	if len(got) != 2 || got[0] != "l2tp-psk-1" || got[1] != "l2tp-psk-2" {
		t.Errorf("conn names are %v, want [l2tp-psk-1 l2tp-psk-2]", got)
	}
	if got := ipsecConnNames(wantIpsecConfPanelWide); len(got) != 1 || got[0] != ipsecConnName {
		t.Errorf("panel-wide conn names are %v, want [%s]", got, ipsecConnName)
	}
	// An unreadable or connless file behaves exactly as the hardcoded name did.
	if got := ipsecConnNames(""); len(got) != 1 || got[0] != ipsecConnName {
		t.Errorf("empty conf gave %v, want the fallback [%s]", got, ipsecConnName)
	}
	// `config setup` is not a conn, and an indented keyword is not a section header.
	if got := ipsecConnNames("config setup\n    uniqueids=no\n  conn indented\n"); got[0] != ipsecConnName {
		t.Errorf("indented text was read as a conn: %v", got)
	}
}

// ---- the save-time check --------------------------------------------------------- //

// seedL2tpInbound stores an inbound the incoming one will be checked against.
func seedL2tpInbound(t *testing.T, id int, listen, settings string) {
	t.Helper()
	inbound := &model.Inbound{
		Id: id, UserId: 1, Tag: fmt.Sprintf("inbound-shared-%d", id), Port: 20000 + id,
		Protocol: model.L2TP, Enable: true, Listen: listen, Remark: fmt.Sprintf("box-%d", id),
		Settings: settings,
	}
	if err := database.GetDB().Create(inbound).Error; err != nil {
		t.Fatalf("seed inbound %d: %v", id, err)
	}
}

func TestL2tpPskConflictOnlyWhenTheIkeListenerIsShared(t *testing.T) {
	for _, tc := range []struct {
		name         string
		otherListen  string
		mineListen   string
		wantConflict bool
	}{
		{"both on every address", "", "", true},
		{"the stored one is on every address", "", "10.0.0.2", true},
		{"the incoming one is on every address", "10.0.0.1", "", true},
		{"both on the same address", "10.0.0.1", "10.0.0.1", true},
		{"an explicit wildcard still covers the other", "0.0.0.0", "10.0.0.2", true},
		{"each on its own address", "10.0.0.1", "10.0.0.2", false},
	} {
		t.Run(tc.name, func(t *testing.T) {
			newInboundDB(t)
			seedL2tpInbound(t, 1, tc.otherListen, `{"ipsecEnable":true,"ipsecPsk":"first-key"}`)

			mine := &model.Inbound{
				Id: 2, Protocol: model.L2TP, Enable: true, Listen: tc.mineListen,
				Settings: `{"ipsecEnable":true,"ipsecPsk":"second-key"}`,
			}
			err := CheckSharedDaemonConflicts(mine, 0)
			if tc.wantConflict != (err != nil) {
				t.Fatalf("conflict=%v (err=%v), want conflict=%v", err != nil, err, tc.wantConflict)
			}
			if err == nil {
				return
			}
			// The message has to name the way out, or the operator's only option is to
			// copy the other inbound's key.
			for _, want := range []string{
				"IPsec pre-shared key", "#1", "box-1", "first-key", "L2TP", "Listen",
			} {
				if !strings.Contains(err.Error(), want) {
					t.Errorf("the refusal never mentions %q: %s", want, err)
				}
			}
		})
	}
}

// Distinct addresses buy a key each and nothing else: DNS and MTU are the one pppd
// options file the single xl2tpd LNS reads, which no address can split up.
func TestL2tpDnsAndMtuConflictRegardlessOfListenAddress(t *testing.T) {
	for _, tc := range []struct {
		name, other, mine, want string
	}{
		{
			"dns", `{"dns1":"1.1.1.1"}`, `{"dns1":"9.9.9.9"}`, "The primary DNS server",
		},
		{
			"mtu", `{"mtu":1400}`, `{"mtu":1300}`, "The MTU",
		},
	} {
		t.Run(tc.name, func(t *testing.T) {
			newInboundDB(t)
			seedL2tpInbound(t, 1, "10.0.0.1", tc.other)

			mine := &model.Inbound{
				Id: 2, Protocol: model.L2TP, Enable: true, Listen: "10.0.0.2", Settings: tc.mine,
			}
			err := CheckSharedDaemonConflicts(mine, 0)
			if err == nil {
				t.Fatalf("two %s values on separate addresses were accepted", tc.name)
			}
			if !strings.Contains(err.Error(), tc.want) {
				t.Errorf("wrong conflict reported: %s", err)
			}
			// The generic message must name the real protocol, not a hardcoded one.
			if !strings.Contains(err.Error(), "every L2TP inbound on this server") {
				t.Errorf("the message does not name the protocol: %s", err)
			}
		})
	}
}
